[package]
name = "ABC-Save-Files"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.204"
erased-serde = "0.4.5"
serde_json = "1.0.120"

[dev-dependencies]
serde = { version = "1.0.204", features = ["derive"] }