[package]
name = "ABC-Save-Files"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.120"
rustc-hash = "2.0.0"
serde = { version = "1.0.204", features = ["derive"] }

[dev-dependencies]
rand = "0.8.4"